name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build, Lint, Format, and Deploy Job
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Set up npm authentication for private packages
      - name: Set up npm authentication
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint and Prettier
      - name: Run ESLint and Prettier
        run: |
          # Run ESLint with --fix to automatically fix issues
          npx eslint . --fix --max-warnings=0

          # Run Prettier with --write to automatically format files
          npx prettier --write .

      # Step 5: Build the app
      - name: Build the app
        run: npm run build

      # Step 6: Deploy the app to Azure Static Web App
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_SMOKE_025A33F0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # API source code path (optional)
          output_location: "dist" # Built app content directory (optional)

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_SMOKE_025A33F0F }}
          action: "close"
